#!/bin/bash
REGEX_IP=\([[:digit:]]\{1,3\}\.\)\{3\}[[:digit:]]\{1,3\}
tail -f /var/log/dovecot.log | egrep '(unknown.user|Password.mismatch)' --line-buffered | grep --color=no $REGX_IP  --line-buffered | sed -u 's/sql(//g; s/)//g; s/,/ /g;' | awk '{printf "%s %s %s %-40s %s\n",$1,$2,$3,$6,$7}' 
