#!/bin/bash
REGX_IP="\([[:digit:]]\{1,3\}\.\)\{3\}[[:digit:]]\{1,3\}"
PATH=/usr/bin:/bin/:/usr/local/scripts/mail/:

# supports -a

mailcop $@ | grep -o "$REGX_IP" | sort | uniq -c | sort -n | awk '{ "geoiplookup " $2 "| cut -f2 -d: " | getline geoip; print $2 "\t\t" $1 " " geoip}'

	
