#!/bin/bash
REGX_IP="\([[:digit:]]\{1,3\}\.\)\{3\}[[:digit:]]\{1,3\}"
PATH=/usr/bin:/bin/:/usr/local/scripts/mail/:

if [[ "$1" == "-a" ]]
then
    mailcop -a | grep -i "$2"
else
    mailcop | grep -i "$1"
fi
