#!/bin/bash
REGX_IP="\([[:digit:]]\{1,3\}\.\)\{3\}[[:digit:]]\{1,3\}"
#echo grep --color=no -o $REGX_IP /tmp/failures | sort | uniq -c | sort -n | awk '{ "geoiplookup " $2 "| cut -f2 -d: " | getline geoip; print $2 "\t\t" $1 " " geoip}'
grep --color=no -o "$REGX_IP" /tmp/failures | sort | uniq -c | sort -n | awk '{ "geoiplookup " $2 "| cut -f2 -d: " | getline geoip; print $2 "\t\t" $1 " " geoip}'
