#!/bin/bash
cd /root/SCRIPTS/MAIL
./mailcop-gen
echo -e "Mailcop" > /tmp/mailcop-stats
echo -e "=======" >> /tmp/mailcop-stats
echo -e "Statistiques des dernières attaques sur notre serveur de messagerie" >> /tmp/mailcop-stats

debut=$(awk 'NR==1 {printf "%s %s %s\n",$1,$2,$3}'  < /tmp/failures)
fin=$(awk 'END{printf "%s %s %s\n",$1,$2,$3}'  < /tmp/failures)

echo -e "Début : $debut" >> /tmp/mailcop-stats
echo -e "Fin   : $fin" >> /tmp/mailcop-stats
echo -e "\n" >> /tmp/mailcop-stats
echo -e "Top 10 des pays" >> /tmp/mailcop-stats
echo -e "---------------" >> /tmp/mailcop-stats



./mailcop-countries | sort -rn  | head >> /tmp/mailcop-stats

echo -e "\n\n" >> /tmp/mailcop-stats

echo -e "Top 10 des addresses IP" >> /tmp/mailcop-stats
echo -e "-----------------------" >> /tmp/mailcop-stats

./mailcop-ips | sort -k 2 -r -n | head | awk '{printf "%-16s %3d %s %s %s %s\n",$1,$2,$3,$4,$5,$6}' >> /tmp/mailcop-stats

echo -e "\n\n" >> /tmp/mailcop-stats
echo -e "Top 10 des logins utilisés" >> /tmp/mailcop-stats
echo -e "--------------------------" >> /tmp/mailcop-stats



./mailcop-logins | sort -nr | head >> /tmp/mailcop-stats


echo -e "\n\n" >> /tmp/mailcop-stats
echo -e "Dernières attaques" >> /tmp/mailcop-stats
echo -e "------------------" >> /tmp/mailcop-stats

./mailcop-static | tail >> /tmp/mailcop-stats

echo -e "\n\n" >> /tmp/mailcop-stats
echo -e "Les 10 dernières addresses bloquées" >> /tmp/mailcop-stats
echo -e "-----------------------------------" >> /tmp/mailcop-stats

/sbin/shorewall show dynamic | sed -n '6p' >> /tmp/mailcop-stats
/sbin/shorewall show dynamic | tail -10 >> /tmp/mailcop-stats

#mailx -s "Mailcop statistics" it_sys@algerian-radio.dz it_head@algerian-radio.dz < /tmp/mailcop-stats
mailx -s "Mailcop statistics" a.chaouche@algerian-radio.dz < /tmp/mailcop-stats

