#!/bin/bash
REGX_IP="\([[:digit:]]\{1,3\}\.\)\{3\}[[:digit:]]\{1,3\}"
if [[ "$#" -ge 1 ]]
then
    files="$@"
else
    files=/var/log/dovecot.log
fi

echo "files=$files"
echo Generating /tmp/failures
zegrep -h '(unknown.user|Password.mismatch)' $files | grep --color=no "$REGX_IP"  > /tmp/failures
echo /tmp/failures generated.
echo now run mailcop-static
