#!/bin/bash

EMAIL="me@myself.com"
# Path to mailcop scripts
PATH="."
$PATH/mailcop-gen
echo -e "Mailcop" > /tmp/mailcop-stats
echo -e "=======" >> /tmp/mailcop-stats
echo -e "Statistiques des dernières attaques sur notre serveur de messagerie" >> /tmp/mailcop-stats

debut=$(awk 'NR==1 {printf "%s %s %s\n",$1,$2,$3}'  < /tmp/failures)
fin=$(awk 'END{printf "%s %s %s\n",$1,$2,$3}'  < /tmp/failures)

echo -e "Début : $debut" >> /tmp/mailcop-stats
echo -e "Fin   : $fin" >> /tmp/mailcop-stats
echo -e "\n" >> /tmp/mailcop-stats
echo -e "Top 10 des pays" >> /tmp/mailcop-stats
echo -e "---------------" >> /tmp/mailcop-stats



$PATH/mailcop-countries | sort -rn  | head >> /tmp/mailcop-stats

echo -e "\n\n" >> /tmp/mailcop-stats

echo -e "Top 10 des addresses IP" >> /tmp/mailcop-stats
echo -e "-----------------------" >> /tmp/mailcop-stats

$PATH/mailcop-ips | sort -k 2 -r -n | head | awk '{printf "%-16s %3d %s %s %s %s\n",$1,$2,$3,$4,$5,$6}' >> /tmp/mailcop-stats

echo -e "\n\n" >> /tmp/mailcop-stats
echo -e "Top 10 des logins utilisés" >> /tmp/mailcop-stats
echo -e "--------------------------" >> /tmp/mailcop-stats



$PATH/mailcop-logins | sort -nr | head >> /tmp/mailcop-stats


echo -e "\n\n" >> /tmp/mailcop-stats
echo -e "Dernières attaques" >> /tmp/mailcop-stats
echo -e "------------------" >> /tmp/mailcop-stats

$PATH/mailcop-static | tail >> /tmp/mailcop-stats


mailx -s "Mailcop statistics" $EMAIL < /tmp/mailcop-stats

